import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import { config } from "../../config";
import { api } from "../../lib/http";
import styles from "../Home/styles.module.css";

interface LoginProps {
  user: any;
}

// export async function getServerSideProps() {
//   const [user] = await Promise.all([
//     fetch(`${config.origin}/auth/me`).then((res) => res.json()),
//   ]);

//   return { props: { user } };
// }

const Home: NextPage<LoginProps> = ({ user }: LoginProps) => {
  const [email, setEmail] = useState<string>();
  const [isPending, setIsPending] = useState(false);
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Doubtful.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Go on. Log in then...</h1>

        <section>
          <form
            action="#"
            onSubmit={async (ev) => {
              ev.preventDefault();
              try {
                setIsPending(true);
                const formData = new FormData(ev.target as HTMLFormElement);
                const code = formData.get("code")?.toString();
                const formEmail = formData.get("email")?.toString() || email;

                if (code) {
                  const ret = (await api
                    .url("/auth/login")
                    .post({ email: formEmail, code })
                    .json()) as { access_token: string };

                  localStorage["doubtful:jwt"] = ret.access_token;

                  router.push('/');
                } else if (formEmail) {
                  await api
                    .url("/auth/login")
                    .post({ email: formEmail, code: "code" })
                    .json();
                  setEmail(formEmail);
                }
              } finally {
                setIsPending(false);
              }
            }}
          >
            {!email ? (
              <>
                <label>Email Address</label>
                <input type="email" name="email" key="email" />
                <button type="submit" disabled={isPending}>
                  Send Code
                </button>
              </>
            ) : (
              <>
                <label>Code</label>
                <input type="text" name="code" maxLength={6} key="code" />
                <button type="submit" disabled={isPending}>
                  Sign Up / In
                </button>
              </>
            )}
          </form>
        </section>
      </main>
    </div>
  );
};

export default Home;
