import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useState } from "react";
import styles from "../styles/Home/styles.module.css";

export const MobilePage: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Doubtful.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title} style={{ fontSize: "20vw" }}>
          Doubtful doesn't support mobile devices.
        </h1>
        <h2
          className={styles.subTitle}
          style={{
            fontSize: "10vw",
            lineHeight: "initial",
            textAlign: "center",
          }}
        >
          Come tell us you want mobile support in{" "}
          <strong>
            <Link
              href="https://chat.whatsapp.com/JeEluh0Czpf3JPu6GPhINx"
              target="_blank"
            >
              the WhatsApp Group
            </Link>
          </strong>
        </h2>
      </main>
    </div>
  );
};

export default MobilePage;
